### PR TITLE
(feat) Added ssh status to prompt

### PR DESCRIPTION
**Pull request by kraem**
Just a small notification abut where you are if you're ssh'd in to a remote machine. Thought it was useful.

### CODE REVIEW

**Comment by umayr** [comment]
Can you add a screenshot as well? Also thanks for the PR. You might also need to update the README as well.

**Comment by kraem** [comment]
Sure! This is not the screen shot you're looking for but here's a problem i am having with the prompt.

I'm having two problems:
1. The right prompt adds a parenthesis when running an empty command.
2. There are two spaces before the lambda sign when logged in remotely.

faulty prompt

Sorry I'm not that good with fish yet. Tried finding the bugs but couldn't. 
Don't know if that's something you could help with. Otherwise you can just deny and close the pull request if you want to.

And; Thanks for an awesome theme!

**Comment by umayr** [comment]
Let me give your patch a try. I'll post an update if I'm able to fix this.

**Comment by alyyousuf7** [comment]
Whites look too bright. I just tried cyan, it looks much better.
Screenshot 2019-09-06 at 6 27 39 pm

**Comment by alyyousuf7** [comment]
I just noticed that there is an extra space in the beginning. It's not visible in the above screenshot.

Here is another variations I tried so that it doesn't look like one big blob of text:
Screenshot 2019-09-06 at 6 51 20 pm

Is `:` better than `@`? I know it's technically not right, but `@` has a big footprint. it just doesn't look good. Probably it's just my terminal font?

I have pushed the changes on my `master` branch. If that looks good, feel free to merge mine. It has `README.md` updated.

**Comment by umayr** [comment]
Merged via #18 

Closing it.

**Pull request closed without merging**
