### PR TITLE
Add terraform workspace name to shell environment

### PR DESCRIPTION
**Pull request by moali87**
This adds terraform workspace name to the shell theme

### CODE REVIEW

**Comment by umayr** [comment]
This is cool. Really appreciated. Can you also update README and add a screenshot to PR? That'd be awesome.

**Comment by moali87** [comment]
Done

**Comment by alyyousuf7** [comment]
@AkhterAli, good job. Just need to point out two things in the `README.md`:
- The screenshot is too small to see whats going on
- Do not commit screenshot image to the repository

**Comment by moali87** [comment]
screen shot 2018-08-01 at 2 16 24 pm

That better?

**Comment by moali87** [comment]
👍 Done

**Comment by moali87** [comment]
Did I miss something?  I'd like to merge this in so I can get back on master branch.  Appreciate it.

**Comment by umayr** [comment]
@AkhterAli Thanks for the PR.

**Pull request merged**
